services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  db-api:
    build: .
    container_name: db-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["uvicorn", "db_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  driver:
    build: .
    container_name: metadata-driver
    volumes:
      - .:/app
    command: sleep infinity
    depends_on:
      - db-api
      - mongo
      - mongo-express
    tty: true

volumes:
  mongo-data:
