services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=secret
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  db-api:
    build: 
      context: db_api
    container_name: db-api
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./db_api/src:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  extractor:
    build: 
      context: meta_extractor
    container_name: extractor
    volumes:
      - ./meta_extractor/src:/app
    command: sleep infinity
    depends_on:
      - db-api
    tty: true

  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/index.html:/app/index.html
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
    working_dir: /app
    command: npm run dev
    depends_on:
      - db-api


volumes:
  mongo-data:
